import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Load CSS tabulator */}
      <link
        rel="stylesheet"
        href="/libs/tabulator-master/dist/css/tabulator.min.css"
      />
      <link
        rel="stylesheet"
        href="/libs/tabulator-master/dist/css/tabulator_midnight.min.css"
      />
      {/* Load JS tabulator */}
      <script src="/libs/tabulator-master/dist/js/tabulator.min.js" />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
